USE final;

/* PART 2: PRIMARY AND FOREIGN KEY SETUP */

# DIM_DRUG #
ALTER TABLE dim_drug MODIFY DRUG_NDC INT(11);
ALTER TABLE dim_drug MODIFY DRUG_NAME VARCHAR(100);
ALTER TABLE dim_drug MODIFY DRUG_FORM_CODE VARCHAR(100);
ALTER TABLE dim_drug MODIFY DRUG_BRAND_GENERIC_CODE INT(11);
ALTER TABLE dim_drug ADD PRIMARY KEY (DRUG_NDC);

# DIM_DRUG_BRAND_GENERIC #
ALTER TABLE dim_drug_brand_generic MODIFY DRUG_BRAND_GENERIC_CODE INT(11);
ALTER TABLE dim_drug_brand_generic MODIFY DRUG_BRAND_GENERIC_DESC VARCHAR(100);
ALTER TABLE dim_drug_brand_generic ADD PRIMARY KEY (DRUG_BRAND_GENERIC_CODE);

# DIM_DRUG_FORM #
ALTER TABLE dim_drug_form MODIFY DRUG_FORM_CODE VARCHAR(100);
ALTER TABLE dim_drug_form MODIFY DRUG_FORM_DESC VARCHAR(100);
ALTER TABLE dim_drug_form ADD PRIMARY KEY (DRUG_FORM_CODE);

# DIM_MEMBER_INFO #
ALTER TABLE dim_member_info MODIFY MEMBER_ID INT(11);
ALTER TABLE dim_member_info MODIFY MEMBER_FIRST_NAME VARCHAR(100);
ALTER TABLE dim_member_info MODIFY MEMBER_LAST_NAME VARCHAR(100);
ALTER TABLE dim_member_info ADD COLUMN MEMBER_BIRTH_DATE_2 DATE;
UPDATE dim_member_info SET MEMBER_BIRTH_DATE_2 = date_format(str_to_date(MEMBER_BIRTH_DATE, '%c/%e/%Y'), '%Y-%m-%d');
ALTER TABLE dim_member_info DROP MEMBER_BIRTH_DATE;
ALTER TABLE dim_member_info RENAME COLUMN MEMBER_BIRTH_DATE_2 TO MEMBER_BIRTH_DATE;
ALTER TABLE dim_member_info MODIFY MEMBER_AGE INT(11);
ALTER TABLE dim_member_info MODIFY MEMBER_GENDER VARCHAR(100);
ALTER TABLE dim_member_info ADD PRIMARY KEY (MEMBER_ID);

# FACT TRANSACTION #
ALTER TABLE fact_transaction MODIFY TRANSACTION_ID INT(11);
ALTER TABLE fact_transaction MODIFY MEMBER_ID INT(11);
ALTER TABLE fact_transaction MODIFY DRUG_NDC INT(11);
ALTER TABLE fact_transaction MODIFY COPAY INT(11);
ALTER TABLE fact_transaction MODIFY INSURANCE_PAID INT(11);
ALTER TABLE fact_transaction ADD COLUMN DATE_FILL_2 DATE;
UPDATE fact_transaction SET DATE_FILL_2 = date_format(str_to_date(DATE_FILL, '%c/%e/%Y'), '%Y-%m-%d');
ALTER TABLE fact_transaction DROP DATE_FILL;
ALTER TABLE fact_transaction RENAME COLUMN DATE_FILL_2 TO DATE_FILL;
ALTER TABLE fact_transaction ADD PRIMARY KEY (TRANSACTION_ID);

# FOREIGN KEY #
ALTER TABLE fact_transaction
ADD FOREIGN KEY FK_MEMBER (MEMBER_ID)
REFERENCES dim_member_info (MEMBER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE fact_transaction
ADD FOREIGN KEY FK_DRUG (DRUG_NDC)
REFERENCES dim_drug (DRUG_NDC)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE dim_drug ADD FOREIGN KEY FK_DRUG_FORM (DRUG_FORM_CODE)
REFERENCES dim_drug_form (DRUG_FORM_CODE)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE dim_drug ADD FOREIGN KEY FK_DRUG_BRAND_GENERIC (DRUG_BRAND_GENERIC_CODE)
REFERENCES dim_drug_brand_generic (DRUG_BRAND_GENERIC_CODE)
ON DELETE CASCADE
ON UPDATE CASCADE;

/* PART 4: ANALYTICS */

# Number of prescriotions grouped by drug name #
SELECT DRUG_NAME, count(TRANSACTION_ID) as PRESCRIPTION_COUNT FROM
(SELECT TRANSACTION_ID, MEMBER_ID, fact_transaction.DRUG_NDC,DRUG_NAME, DATE_FILL FROM fact_transaction 
INNER JOIN dim_drug
ON fact_transaction.DRUG_NDC = dim_drug.DRUG_NDC) u 
GROUP BY DRUG_NAME;

# Query for age group #
DROP TABLE IF EXISTS final.AGE;
CREATE TABLE AGE 
(SELECT a.*, b.MEMBER_AGE FROM dim_member_info as b
LEFT JOIN fact_transaction AS a 
ON a.MEMBER_ID = b.MEMBER_ID);


SELECT CASE WHEN MEMBER_AGE > 65 THEN 'AGE OVER 65'
			WHEN MEMBER_AGE < 65 THEN 'AGE BELOW 65'
			END AS AGE_GROUP,
COUNT(MEMBER_ID) AS TOTAL_PRESCRIPTION,
COUNT(DISTINCT MEMBER_ID) AS UNIQUE_MEMBER,
SUM(COPAY) AS TOTAL_COPAY, 
SUM(INSURANCE_PAID) AS TOTAL_INSURANCE_PAID
FROM AGE
GROUP BY AGE_GROUP;

# Most recent prescription fill date #
DROP TABLE IF EXISTS final.TABLE_1;
CREATE TABLE TABLE_1
(SELECT MEMBER_ID, 
		MEMBER_FIRST_NAME, 
        MEMBER_LAST_NAME
FROM dim_member_info);

DROP TABLE IF EXISTS final.TABLE_2;
CREATE TABLE TABLE_2
(SELECT MEMBER_ID,
		DRUG_NDC, 
        DATE_FILL AS MR_DATE_FILL,
        INSURANCE_PAID,
		row_number() OVER (PARTITION BY MEMBER_ID ORDER BY DATE_FILL DESC) AS NOTE
FROM fact_transaction);

SELECT TABLE_1.*, D.DRUG_NAME, TABLE_2.MR_DATE_FILL, TABLE_2.INSURANCE_PAID as MR_INSURANCE_PAID
FROM TABLE_1
LEFT JOIN TABLE_2 ON TABLE_2.MEMBER_ID = TABLE_1.MEMBER_ID
LEFT JOIN dim_drug AS D ON D.DRUG_NDC = TABLE_2.DRUG_NDC
WHERE TABLE_2.NOTE = 1;
